version: "3.9"

volumes:
  simple-files:
    external: true
  mysql_db:

services:
  webapp:
    image: simple-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "run", "dev"]
    ports:
      - "80:3000"
    volumes:
      - .:/app
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"